[package]
name = "octo-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
arcs-env-rs = "0.1.0"
arcs-logging-rs = "0.1.2"

tokio = { version = "1.21.2", features = ["macros", "rt", "full"] }

async-graphql = { version = "6.0.5", features = ["uuid", "chrono", "tokio"] }
graphql_client = "0.13.0"
futures = "0.3.28"

fcm = "0.9.2"
reqwest = {version = "0.11.20", features=["json"]}
juniper = "0.15.11"
serde = "1.0.188"
uuid = "1.4.1"
chrono = "0.4.30"
actix-web = "4.4.0"
lazy_static = "1.4.0"
